services:

  # 1. AI Service
  - type: web
    name: scout-arena-ai
    env: python
    rootDir: ai-service
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app


  # 2. Backend
  - type: web
    name: scout-arena-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js

    envVars:

      - key: MONGO_URI
        sync: false

      - key: JWT_SECRET
        generateValue: true

      - key: AI_SERVICE_URL
        fromService:
          name: scout-arena-ai
          type: web
          property: url

      - key: CLIENT_URL
        fromService:
          name: scout-arena-frontend
          type: web
          property: url



  # 3. Frontend (STATIC SITE FIXED)
  - type: web
    name: scout-arena-frontend
    env: static

    rootDir: frontend

    buildCommand: npm install && npm run build

    staticPublishPath: dist


    envVars:

      - key: NODE_VERSION
        value: 20.11.0


      - key: VITE_API_URL
        fromService:
          name: scout-arena-backend
          type: web
          property: url
        suffix: /api


      - key: VITE_SOCKET_URL
        fromService:
          name: scout-arena-backend
          type: web
          property: url