services:

  # 1. AI Service
  - type: web
    name: scout-arena-ai
    env: python
    rootDir: ai-service
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app



  # 2. Backend
  - type: web
    name: scout-arena-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js

    envVars:

      - key: MONGO_URI
        sync: false

      - key: JWT_SECRET
        generateValue: true

      - key: AI_SERVICE_URL
        value: https://scout-arena-ai.onrender.com

      - key: CLIENT_URL
        value: https://scout-arena-frontend.onrender.com




  # 3. Frontend
  - type: web
    name: scout-arena-frontend
    env: static
    rootDir: frontend

    buildCommand: npm install && npm run build

    staticPublishPath: dist


    envVars:

      - key: NODE_VERSION
        value: 20.11.0


      - key: VITE_API_URL
        value: https://scout-arena-backend.onrender.com/api


      - key: VITE_SOCKET_URL
        value: https://scout-arena-backend.onrender.com